server {
    listen 80;

    # React Static Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Proxy to Backend1
    location /addExchangeRate {
        proxy_pass http://host.docker.internal:8080;
    }

    location /getAmount {
        proxy_pass http://host.docker.internal:8080;
    }

    location /getTotalCount {
        proxy_pass http://host.docker.internal:8080;
    }
}